name: 'Build and deploy'

on:
  push:
    branches:
      - 'develop'

env:
  PROJECT_ID: '${{ secrets.DEV_GCP_PROJECT_ID }}'
  SERVICE_ACCOUNT: '${{secrets.DEV_GCP_SERVICE_ACCOUNT}}'
  JOB_NAME: 'python-job'
  REGION: '${{secrets.DEV_GCP_REGION}}'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{secrets.DEV_GCP_WORKLOAD_IDENTITY_PROVIDER}}'
          service_account: '${{env.DEV_GCP_SERVICE_ACCOUNT}}'
      - name: 'Setup GCP client'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: '${{ env.DEV_GCP_PROJECT_ID }}'
      - name: 'Authorize Docker push'
        run: 'gcloud auth configure-docker'
      - name: 'Build and Push Container'
        run: |-
          docker build -t gcr.io/${{ env.DEV_GCP_PROJECT_ID }}/${{ env.JOB_NAME }}:${{  github.sha }} .
          docker push gcr.io/${{ env.DEV_GCP_PROJECT_ID }}/${{ env.JOB_NAME }}:${{  github.sha }}
